yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'change_password/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='change_password'
    ),
    path(
        'change_password/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='change_password_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    import debug_toolbar
    
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),) 

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

yatube/templates/includes/comments.html
{% load user_filters %}
{% block content %}

{% if user.is_authenticated %}
<div class="card my-4">
  <h5 class="card-header">Добавить комментарий:</h5>
  <div class="card-body">
      {% include 'includes/form.html' with action_url='posts:add_comment' post_id=selected_post.id %}
      <button type="submit" class="btn btn-primary">Отправить</button>
    </form>
  </div>
</div>
{% endif %}

<h5 class="px-4">Комментарии:</h5><hr>
{% for comment in comments %}
<div class="media ml-4 px-4">
  <div class="media-body">
    <h5 class="mt-0">
      <a href="{% url 'posts:profile' comment.author.username %}">
         {{ comment.author.get_full_name }}
      </a>
    </h5>
    <p>
      {{ comment.text }}
    </p>
    {% if not forloop.last %}
      <hr>
    {% endif %}
  </div>
</div>
{% endfor %}
{% endblock %}

yatube/templates/includes/end_notion.html
</div>
</div>
</div>
</div>
</div>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
</footer>

yatube/templates/includes/form.html
<div class="card-body">
    {% load user_filters %}
    {% if form.errors %}
        {% for field in form %}
          {% for error in field.errors %}            
            <div class="alert alert-danger">
              {{ error|escape }}
            </div>
          {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
            {{ error|escape }}
          </div>
        {% endfor %}
    {% endif %}

    <form method="post"
      {% if post_id %}
          {% if action_url %}
            action="{% url action_url post_id %}"
          {% endif %}
      {% else %}
          {% if action_url %}
            action="{% url action_url %}"
          {% endif %}
      {% endif %}
      enctype="multipart/form-data"
    >
    {% csrf_token %}

    {% for field in form %}
      <div class="form-group row my-3"
        {% if field.field.required %} 
          aria-required="true"
        {% else %}
          aria-required="false"
        {% endif %}
      >
        <label for="{{ field.id_for_label }}">
          {{ field.label }}
            {% if field.field.required %}
              <span class="required text-danger">*</span>
            {% endif %}
        </label>
        <div>
        {{ field|addclass:'form-control' }}
          {% if field.help_text %}
            <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
              {{ field.help_text|safe }}
            </small>
          {% endif %}
        </div>
      </div>
    {% endfor %}

yatube/templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      <ul class="nav nav-pills">
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" 
            href="{% url 'about:author' %}">
            Об авторе
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" 
            href="{% url 'about:tech' %}">
            Технологии
          </a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'posts:post_create' or view_name  == 'posts:post_edit'%}active{% endif %}" 
            href="{% url 'posts:post_create' %}">
            Новая запись
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'users:change_password' %}active{% endif %}" 
            href="{% url 'users:change_password' %}">
            Изменить пароль
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:logout' %}">
            Выйти
          </a>
        </li>
        <li class="my-2">
          Пользователь: {{ user.username }}
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'users:login' %}active{% endif %}" 
            href="{% url 'users:login' %}">
            Войти
          </a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'users:signup' %}active{% endif %}" 
            href="{% url 'users:signup' %}">
            Регистрация
          </a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>      
</header>
{% endwith %}

yatube/templates/includes/start_notion.html
<div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
          <div class="card">