yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    import debug_toolbar
    
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),) 

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    """View-класс для рендера страницы автора сайта."""

    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    """View-класс для рендера страницы используемого стека."""

    template_name = 'about/tech.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1 class="mx-5">Привет, я автор</h1>
<p class="mx-5">
  На данный момент являюсь студетом Яндекс.Практиктум на курсе backend-разработчик.
  Изучаю перечисленный <a href="{% url 'about:tech' %}">тут</a> стек технологий. 
  <br>Вы можете посмотреть мой Гитхаб по
  <a href="https://github.com/egorkomel">ссылке.</a>
  <br>
</p>
{% endblock %} 

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
<div class="row">
  <h1>Вот что я умею</h1>
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        ООП
      </li>
      <li class="list-group-item">
        Django
      </li>
      <li class="list-group-item">
        ORM
      </li>
      <li class="list-group-item">
        SQL
      </li>
      <li class="list-group-item">
        Git
      </li>
      <li class="list-group-item">
        Linux
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <p>
      Изучаю перечисленный слева стек технологий, а также многое другое. Хочу знать больше, расти и быть
      восстребованным на рынке.
    </p>
  </article>
</div>
{% endblock %} 