yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    import debug_toolbar
    
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),) 

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    """Модель групп."""

    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return f'Группа {self.title}'


class Post(CreatedModel):
    """Модель постов."""

    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(CreatedModel):
    """Модель комментариев."""

    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    text = models.TextField(
        verbose_name='Текст комменатрия',
        help_text='Введите текст комментария'
    )


class Follow(models.Model):
    """Модель для подписок."""

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

    class Meta:
        db_table = 'posts_follow'
        constraints = [
            models.UniqueConstraint(
                fields=['author_id', 'user_id'], name='unique follow'
            )
        ]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    """Форма для создания нового поста."""

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['group'].empty_label = '--- Выберите группу ---'

    def clean_text(self):
        data = self.cleaned_data['text']
        if data == '':
            raise forms.ValidationError('Текст поста отсутствует!')
        return data


class CommentForm(forms.ModelForm):
    """Модель для созданиея нового комментария."""

    class Meta:
        model = Comment
        fields = ('text',)

    def clean_text(self):
        data = self.cleaned_data['text']
        if data == '':
            raise forms.ValidationError('Текст комментария отсутствует!')
        return data

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .utils import make_paginator

MAX_POSTS = 10


def index(request):
    """View-функция для рендера главной страницы."""
    template = 'posts/index.html'
    posts = Post.objects.all()
    page_obj = make_paginator(request, posts, MAX_POSTS)
    return render(request, template, context={'page_obj': page_obj})


def group_posts(request, slug):
    """View-функция для рендера постов в конкртеной группе."""
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = make_paginator(request, posts, MAX_POSTS)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    """View-функция для рендера профайла пользователя."""
    temmplate = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    count_posts = posts.count()
    page_obj = make_paginator(request, posts, MAX_POSTS)
    following = False
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            author=author,
            user=request.user
        ).exists()
    context = {
        'author': author,
        'count_posts': count_posts,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, temmplate, context)


def post_detail(request, post_id):
    """View-функция для рендера страницы поста."""
    temmplate = 'posts/post_detail.html'
    selected_post = get_object_or_404(
        Post.objects.select_related('group', 'author',),
        pk=post_id
    )
    count_posts = selected_post.author.posts.count()
    comments = selected_post.comments.all()
    form = CommentForm()
    context = {
        'count_posts': count_posts,
        'selected_post': selected_post,
        'comments': comments,
        'form': form,
    }
    return render(request, temmplate, context)


@login_required
def post_create(request):
    """View-функция для рендера страницы создания поста."""
    template = 'posts/post_create.html'
    form = PostForm(request.POST or None, files=request.FILES or None)
    if request.method == 'POST':
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()
            return redirect('posts:profile', username=f'{request.user}')
    return render(request, template, context={'form': form})


@login_required
def post_edit(request, post_id):
    """View-функция для рендера страницы редактирования поста."""
    template = 'posts/post_create.html'
    post_for_edit = get_object_or_404(Post, pk=post_id)
    if post_for_edit.author == request.user:
        form = PostForm(
            request.POST or None,
            files=request.FILES or None,
            instance=post_for_edit
        )
        if request.method == 'POST':
            if form.is_valid():
                updated_post = form.save(commit=False)
                updated_post.author = request.user
                updated_post.save()
                return redirect('posts:post_detail', post_id=f'{post_id}')
    else:
        return redirect('posts:post_detail', post_id=f'{post_id}')
    context = {
        'is_edit': True,
        'form': form,
    }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    """Добавить комментарий в БД и выполнить редирект."""
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """View-функция для вывода постов авторов,
    на которых user подписан.
    """
    template = 'posts/follow.html'
    posts = Post.objects.filter(author__following__user=request.user)
    page_obj = make_paginator(request, posts, MAX_POSTS)
    return render(request, template, context={'page_obj': page_obj})


@login_required
def profile_follow(request, username):
    """Подписаться на автора и выполнить редиркет."""
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.update_or_create(
            author=author,
            user=request.user
        )
    return redirect('posts:follow_index')


@login_required
def profile_unfollow(request, username):
    """Отписаться от автора и выполнить редиркет."""
    Follow.objects.filter(
        user=request.user,
        author=get_object_or_404(User, username=username)
    ).delete()
    return redirect('posts:follow_index')

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail cache %}

{% block title %}
  Подписки
{% endblock %}

{% block content %}
  <h1 class="container">
    Подписки
  </h1>
  {% include 'posts/includes/switcher.html' %}

  {% cache 20 follow_page request.user.username %}
  {% for post in page_obj %}
  <div class="container">
  <article>
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        <a href="{% url 'posts:profile' post.author %}">Все посты пользователя {{ post.author.get_full_name }}</a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date | date:"d E y"}}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>
      {{ post.text }}
    </p>
    <a href="{% url 'posts:post_detail' post.pk %}">Подробнее</a>  
  </article>
  {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы {{ post.group.title }}</a>
  {% endif %}
</div>

    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endcache %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  {{ group.title }}
{% endblock %}

{% block content %}
<div class="container">
  {% block header %}
    <h1>
      {{ group.title }}
    </h1> 
  {% endblock %}
  <p>
    {{ group.description }}
  </p>
</div>
  {% for post in page_obj %}
  <main>
    <div class="container">
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            <a href="{% url 'posts:profile' post.author %}">Все посты пользователя {{ post.author.get_full_name }}</a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E y"}}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}   
        <p>
          {{ post.text }}
        </p>
        <a href="{% url 'posts:post_detail' post.pk %}">Подробнее</a>    
      </article>
      {% if not forloop.last %}
        <hr>
      {% endif %}
    </div>  
  </main>
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail cache %}

{% block title %}
  Последние обновления на сайте
{% endblock %}

{% block content %}
  <h1 class="container">
    Последние обновления на сайте
  </h1>
  {% include 'posts/includes/switcher.html' %}

  {% cache 20 index_page %}
  {% for post in page_obj %}
  <div class="container">
  <article>
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        <a href="{% url 'posts:profile' post.author %}">Все посты пользователя {{ post.author.get_full_name }}</a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date | date:"d E y"}}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>
      {{ post.text }}
    </p>
    <a href="{% url 'posts:post_detail' post.pk %}">Подробнее</a>  
  </article>
  {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы {{ post.group.title }}</a>
  {% endif %}
</div>

    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %}
  {% endcache %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_create.html
{% extends "base.html" %}
{% block title %}
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %} 
{% endblock %}
{% block content %}   
{% include 'includes/start_notion.html' %}
<div class="card-header">       
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %}             
</div>
{% include 'includes/form.html' %}
  <div class="d-flex justify-content-end">
    <button type="submit" class="btn btn-primary">
      {% if is_edit %}
        Сохранить
      {% else %}
        Добавить
      {% endif %} 
    </button>
  </div>
</form>
{% include 'includes/end_notion.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Пост {{ selected_post.text|slice:30 }}
{% endblock %}
{% block content %}
<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Дата публикации: {{ selected_post.pub_date | date:"d E y" }}
      </li>
      {% if selected_post.group %} 
      <li class="list-group-item">
        Группа: {{ selected_post.group }}
      </li>
      <li class="list-group-item">
        <a href="{% url 'posts:group_list' selected_post.group.slug %}">
          Все записи группы {{ selected_post.group.title }}
        </a>
      {% endif %}
      </li>
      <li class="list-group-item">
        Автор: {{ selected_post.author.get_full_name }}
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Всего постов автора:  <span >{{ count_posts }}</span>
      </li>
      <li class="list-group-item">
        <a href="{% url 'posts:profile' selected_post.author %}">
          Все посты пользователя {{ selected_post.author.get_full_name }}
        </a>
      </li>
    </ul>
  </aside>

  <article class="col-12 col-md-9">
    {% thumbnail selected_post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>
      {{ selected_post.text }}
    </p>
    {% if user == selected_post.author %}
    <a class="btn btn-primary" href="{% url 'posts:post_edit' selected_post.pk %}">
      Редактировать запись
    </a>
    {% endif %}
  </article>
</div>
{% include 'includes/comments.html' %}
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock %}
{% block content %}
  <h1 class="container">
    Все посты пользователя {{ author.get_full_name }}
  </h1>
  <h3 class="container">Всего постов: {{ count_posts }}</h3> 

  <div class="mb-5 container">
    {% if request.user != author %}
    {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button"
      >
        Отписаться
      </a>
    {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
     {% endif %}
     {% endif %}
  </div>

        {% for post in page_obj %}
        <div class="container">
        <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E y"}}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p >
          {{ post.text }}
        </p>
        <a href="{% url 'posts:post_detail' post.pk %}">Подробная информация </a>
      </article>
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы {{ post.group.title }}</a>
        {% endif %}
    </div>
        {% if not forloop.last %}
          <hr>
        {% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
      </div>
{% endblock %}